### ISSUE TITLE
just hide the parent

### ISSUE THREAD

**Issue by rimmesbe** [SeanTankGarvey/f1-3-c2p1-colmar-academy#2]
You have the mobile class in every element, just put it in the parent of the section you want to hide. This will take some bloat out of your html.

https://github.com/SeanTankGarvey/f1-3-c2p1-colmar-academy/blob/master/ColmarAcademy-Capstone/index.html#L101-L120

**Comment by SeanTankGarvey** [comment]
Good point. Agreed. I also did the same thing with the desktop class too.
