### ISSUE TITLE
class names

### ISSUE THREAD

**Issue by rimmesbe** [SeanTankGarvey/f1-3-c2p1-colmar-academy#4]
Some of these class names are a little too generic. You really don't want to start putting numbers in your class names, try to make them descriptive. It's okay to make class names long:
.large-column__sixty
.side-column__img
.side-column__text
I would check out some official naming conventions and choose one you like.

https://github.com/SeanTankGarvey/f1-3-c2p1-colmar-academy/blob/master/ColmarAcademy-Capstone/resources/css/style.css#L278

**Comment by SeanTankGarvey** [comment]
So descriptive over simplistic, okay. Do you have a recommendation of a certain naming convention or if not it seems like BEM is very popular..?

**Comment by rimmesbe** [comment]
Yes I like BEM.
