### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [SeanTankGarvey/f1-3-c2p1-colmar-academy#6]
Grade: Satisfactory

Summary: Nice job on this final project, the end results look good. The mobile also looks very good. Your code was well organized and you used a lot of good techniques. I created a few issues of some minor tweaks and good practice suggestions that you should look into. In regards to naming convention, I like BEM but there are many different ones. Adopting one will help you make your code more readable and organized: http://getbem.com/introduction/
Image tags can be tough to wrangle. There are different techniques to do this but usually wrapping them is a good idea. https://internetingishard.com/html-and-css/responsive-images/
It would also be cool to see some transitions used to give the site a little life.

Overall nice job, I hope you enjoyed the course.

**Comment by SeanTankGarvey** [comment]
Thank you very much. At some point maybe I will add transitions, but I was more focused on the refactoring and getting the visual components/presentation correct.  Also, I am not sure if I did the ARIA stuff correct, but I think I did. That is a work in progress.
